services:
  db:
    image: postgres
    ports:
      - 5432:5432
    #container_name: postgres-db
    networks:
      - backend
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - /home/da3m0n/py-automation/app/db/data:/var/lib/postgresql/data
  backend_api:
    image: py-automation-backend
    pull_policy: if_not_present
    container_name: python_api
    volumes:
      - /home/da3m0n/scripts/data:/app/scripts/data
    networks:
      - frontend
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-1-https.rule=Host(`dashboard.tuschkoreit.de`)
      - traefik.http.routers.api-1-https.entrypoints=websecure
      - traefik.http.routers.api-1-https.tls=true
      - traefik.http.routers.api-1-https.tls.certresolver=cloudflare
      - traefik.http.services.api-1-https-service.loadbalancer.server.port=5000
    restart: unless-stopped
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    #container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USERNAME}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'True'
      PGADMIN_CONFIG_ALLOWED_HOSTS: '["pgadmin.tuschkoreit.de"]'
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin-https.rule=Host(`pgadmin.tuschkoreit.de`)
      - traefik.http.routers.pgadmin-https.entrypoints=websecure
      - traefik.http.routers.pgadmin-https.tls=true
      - traefik.http.routers.pgadmin-https.tls.certresolver=cloudflare
      - traefik.http.services.pgadmin-https-service.loadbalancer.server.port=80
    networks:
      - backend
      - frontend
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes: 
      - /home/da3m0n/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.kuma.rule=Host(`status.tuschkoreit.de`)
      - traefik.http.routers.kuma.entrypoints=websecure
      - traefik.http.routers.kuma.tls=true
      - traefik.http.routers.kuma.tls.certresolver=cloudflare
      - traefik.http.services.kuma.loadbalancer.server.port=3001
    ports:
      - 3001:3001
    restart: unless-stopped
  
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
    restart: unless-stopped

networks:
  frontend:
    external: true
  backend:
    external: false
