services:
  backend_api:
    image: py-automation-backend
    pull_policy: if_not_present
    container_name: backend
    networks:
    - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-1-https.rule=Host(`dashboard.tuschkoreit.de`)
      - traefik.http.routers.api-1-https.entrypoints=websecure
      - traefik.http.routers.api-1-https.tls=true
      - traefik.http.routers.api-1-https.tls.certresolver=cloudflare
      - traefik.http.services.api-1-https-service.loadbalancer.server.port=5000
    restart: unless-stopped
networks:
  frontend:
    external: true

